// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type Composable, type TDataShape, type Client, urlSearchParamsBodySerializer } from './client';
import type { LegacyLoginAuthLoginPostData, LegacyLoginAuthLoginPostResponse, LegacyLoginAuthLoginPostError, LogoutAuthLogoutPostData, LogoutAuthLogoutPostResponse, LogoutAuthLogoutPostError, GetCsrfTokenAuthCsrfTokenGetData, GetCsrfTokenAuthCsrfTokenGetResponse, GetCsrfTokenAuthCsrfTokenGetError, GetAuthenticatedUserinfoUserGetData, GetAuthenticatedUserinfoUserGetResponse, GetAuthenticatedUserinfoUserGetError, UpdateAuthenticatedUserinfoUserPatchData, UpdateAuthenticatedUserinfoUserPatchResponse, UpdateAuthenticatedUserinfoUserPatchError, GetUsersUsersGetData, GetUsersUsersGetResponse, GetUsersUsersGetError, CreateUserUsersPostData, CreateUserUsersPostResponse, CreateUserUsersPostError, DeleteUserUsersUserIdDeleteData, DeleteUserUsersUserIdDeleteResponse, DeleteUserUsersUserIdDeleteError, GetUserUsersUserIdGetData, GetUserUsersUserIdGetResponse, GetUserUsersUserIdGetError, UpdateUserUsersUserIdPatchData, UpdateUserUsersUserIdPatchResponse, UpdateUserUsersUserIdPatchError, SetUserRolesUsersUserIdRolesPutData, SetUserRolesUsersUserIdRolesPutResponse, SetUserRolesUsersUserIdRolesPutError, GetAllPermissionsPermissionsGetData, GetAllPermissionsPermissionsGetResponse, GetAllPermissionsPermissionsGetError, GetRolesRolesGetData, GetRolesRolesGetResponse, GetRolesRolesGetError, CreateRoleRolesPostData, CreateRoleRolesPostResponse, CreateRoleRolesPostError, DeleteRoleRolesRoleIdDeleteData, DeleteRoleRolesRoleIdDeleteResponse, DeleteRoleRolesRoleIdDeleteError, GetRoleDetailRolesRoleIdGetData, GetRoleDetailRolesRoleIdGetResponse, GetRoleDetailRolesRoleIdGetError, UpdateRoleRolesRoleIdPatchData, UpdateRoleRolesRoleIdPatchResponse, UpdateRoleRolesRoleIdPatchError, SetRolePermissionsRolesRoleIdPermissionsPutData, SetRolePermissionsRolesRoleIdPermissionsPutResponse, SetRolePermissionsRolesRoleIdPermissionsPutError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TComposable extends Composable, TData extends TDataShape = TDataShape, ResT = unknown, DefaultT = undefined> = ClientOptions<TComposable, TData, ResT, DefaultT> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Legacy Login
 * ⏱️ Rate limit: `10 per 1 minute`
 */
export const legacyLoginAuthLoginPost = <TComposable extends Composable, DefaultT extends LegacyLoginAuthLoginPostResponse = LegacyLoginAuthLoginPostResponse>(options: Options<TComposable, LegacyLoginAuthLoginPostData, LegacyLoginAuthLoginPostResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).post<TComposable, LegacyLoginAuthLoginPostResponse | DefaultT, LegacyLoginAuthLoginPostError, DefaultT>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Logout
 * ⏱️ Rate limit: `10 per 1 minute`
 */
export const logoutAuthLogoutPost = <TComposable extends Composable, DefaultT extends LogoutAuthLogoutPostResponse = LogoutAuthLogoutPostResponse>(options: Options<TComposable, LogoutAuthLogoutPostData, LogoutAuthLogoutPostResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).post<TComposable, LogoutAuthLogoutPostResponse | DefaultT, LogoutAuthLogoutPostError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/auth/logout',
        ...options
    });
};

/**
 * Get Csrf Token
 * ⏱️ Rate limit: `30 per 1 minute`
 */
export const getCsrfTokenAuthCsrfTokenGet = <TComposable extends Composable, DefaultT extends GetCsrfTokenAuthCsrfTokenGetResponse = GetCsrfTokenAuthCsrfTokenGetResponse>(options: Options<TComposable, GetCsrfTokenAuthCsrfTokenGetData, GetCsrfTokenAuthCsrfTokenGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetCsrfTokenAuthCsrfTokenGetResponse | DefaultT, GetCsrfTokenAuthCsrfTokenGetError, DefaultT>({
        url: '/auth/csrf-token',
        ...options
    });
};

/**
 * Get Authenticated Userinfo
 * ⏱️ Rate limit: `60 per 1 minute`
 */
export const getAuthenticatedUserinfoUserGet = <TComposable extends Composable, DefaultT extends GetAuthenticatedUserinfoUserGetResponse = GetAuthenticatedUserinfoUserGetResponse>(options: Options<TComposable, GetAuthenticatedUserinfoUserGetData, GetAuthenticatedUserinfoUserGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetAuthenticatedUserinfoUserGetResponse | DefaultT, GetAuthenticatedUserinfoUserGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/user',
        ...options
    });
};

/**
 * Update Authenticated Userinfo
 * ⏱️ Rate limit: `60 per 1 minute`
 */
export const updateAuthenticatedUserinfoUserPatch = <TComposable extends Composable, DefaultT extends UpdateAuthenticatedUserinfoUserPatchResponse = UpdateAuthenticatedUserinfoUserPatchResponse>(options: Options<TComposable, UpdateAuthenticatedUserinfoUserPatchData, UpdateAuthenticatedUserinfoUserPatchResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).patch<TComposable, UpdateAuthenticatedUserinfoUserPatchResponse | DefaultT, UpdateAuthenticatedUserinfoUserPatchError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Users
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:read`
 */
export const getUsersUsersGet = <TComposable extends Composable, DefaultT extends GetUsersUsersGetResponse = GetUsersUsersGetResponse>(options: Options<TComposable, GetUsersUsersGetData, GetUsersUsersGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetUsersUsersGetResponse | DefaultT, GetUsersUsersGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users',
        ...options
    });
};

/**
 * Create User
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:create`
 */
export const createUserUsersPost = <TComposable extends Composable, DefaultT extends CreateUserUsersPostResponse = CreateUserUsersPostResponse>(options: Options<TComposable, CreateUserUsersPostData, CreateUserUsersPostResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).post<TComposable, CreateUserUsersPostResponse | DefaultT, CreateUserUsersPostError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete User
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:delete`
 */
export const deleteUserUsersUserIdDelete = <TComposable extends Composable, DefaultT extends DeleteUserUsersUserIdDeleteResponse = DeleteUserUsersUserIdDeleteResponse>(options: Options<TComposable, DeleteUserUsersUserIdDeleteData, DeleteUserUsersUserIdDeleteResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).delete<TComposable, DeleteUserUsersUserIdDeleteResponse | DefaultT, DeleteUserUsersUserIdDeleteError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Get User
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:read`
 */
export const getUserUsersUserIdGet = <TComposable extends Composable, DefaultT extends GetUserUsersUserIdGetResponse = GetUserUsersUserIdGetResponse>(options: Options<TComposable, GetUserUsersUserIdGetData, GetUserUsersUserIdGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetUserUsersUserIdGetResponse | DefaultT, GetUserUsersUserIdGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Update User
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:update`
 */
export const updateUserUsersUserIdPatch = <TComposable extends Composable, DefaultT extends UpdateUserUsersUserIdPatchResponse = UpdateUserUsersUserIdPatchResponse>(options: Options<TComposable, UpdateUserUsersUserIdPatchData, UpdateUserUsersUserIdPatchResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).patch<TComposable, UpdateUserUsersUserIdPatchResponse | DefaultT, UpdateUserUsersUserIdPatchError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Set User Roles
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:update`
 */
export const setUserRolesUsersUserIdRolesPut = <TComposable extends Composable, DefaultT extends SetUserRolesUsersUserIdRolesPutResponse = SetUserRolesUsersUserIdRolesPutResponse>(options: Options<TComposable, SetUserRolesUsersUserIdRolesPutData, SetUserRolesUsersUserIdRolesPutResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).put<TComposable, SetUserRolesUsersUserIdRolesPutResponse | DefaultT, SetUserRolesUsersUserIdRolesPutError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All Permissions
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `permissions:read`, `users`, `roles`
 */
export const getAllPermissionsPermissionsGet = <TComposable extends Composable, DefaultT extends GetAllPermissionsPermissionsGetResponse = GetAllPermissionsPermissionsGetResponse>(options: Options<TComposable, GetAllPermissionsPermissionsGetData, GetAllPermissionsPermissionsGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetAllPermissionsPermissionsGetResponse | DefaultT, GetAllPermissionsPermissionsGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/permissions',
        ...options
    });
};

/**
 * Get Roles
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:read`
 */
export const getRolesRolesGet = <TComposable extends Composable, DefaultT extends GetRolesRolesGetResponse = GetRolesRolesGetResponse>(options: Options<TComposable, GetRolesRolesGetData, GetRolesRolesGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetRolesRolesGetResponse | DefaultT, GetRolesRolesGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles',
        ...options
    });
};

/**
 * Create Role
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:create`
 */
export const createRoleRolesPost = <TComposable extends Composable, DefaultT extends CreateRoleRolesPostResponse = CreateRoleRolesPostResponse>(options: Options<TComposable, CreateRoleRolesPostData, CreateRoleRolesPostResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).post<TComposable, CreateRoleRolesPostResponse | DefaultT, CreateRoleRolesPostError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete Role
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:delete`
 */
export const deleteRoleRolesRoleIdDelete = <TComposable extends Composable, DefaultT extends DeleteRoleRolesRoleIdDeleteResponse = DeleteRoleRolesRoleIdDeleteResponse>(options: Options<TComposable, DeleteRoleRolesRoleIdDeleteData, DeleteRoleRolesRoleIdDeleteResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).delete<TComposable, DeleteRoleRolesRoleIdDeleteResponse | DefaultT, DeleteRoleRolesRoleIdDeleteError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options
    });
};

/**
 * Get Role Detail
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:read`
 */
export const getRoleDetailRolesRoleIdGet = <TComposable extends Composable, DefaultT extends GetRoleDetailRolesRoleIdGetResponse = GetRoleDetailRolesRoleIdGetResponse>(options: Options<TComposable, GetRoleDetailRolesRoleIdGetData, GetRoleDetailRolesRoleIdGetResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).get<TComposable, GetRoleDetailRolesRoleIdGetResponse | DefaultT, GetRoleDetailRolesRoleIdGetError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options
    });
};

/**
 * Update Role
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:update`
 */
export const updateRoleRolesRoleIdPatch = <TComposable extends Composable, DefaultT extends UpdateRoleRolesRoleIdPatchResponse = UpdateRoleRolesRoleIdPatchResponse>(options: Options<TComposable, UpdateRoleRolesRoleIdPatchData, UpdateRoleRolesRoleIdPatchResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).patch<TComposable, UpdateRoleRolesRoleIdPatchResponse | DefaultT, UpdateRoleRolesRoleIdPatchError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Set Role Permissions
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:update`
 */
export const setRolePermissionsRolesRoleIdPermissionsPut = <TComposable extends Composable, DefaultT extends SetRolePermissionsRolesRoleIdPermissionsPutResponse = SetRolePermissionsRolesRoleIdPermissionsPutResponse>(options: Options<TComposable, SetRolePermissionsRolesRoleIdPermissionsPutData, SetRolePermissionsRolesRoleIdPermissionsPutResponse, DefaultT>) => {
    return (options.client ?? _heyApiClient).put<TComposable, SetRolePermissionsRolesRoleIdPermissionsPutResponse | DefaultT, SetRolePermissionsRolesRoleIdPermissionsPutError, DefaultT>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};