// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from './client';
import type { AuthLegacyLoginData, AuthLegacyLoginResponses, AuthLegacyLoginErrors, AuthLogoutData, AuthLogoutResponses, AuthLogoutErrors, AuthGetCsrfTokenData, AuthGetCsrfTokenResponses, AuthGetCsrfTokenErrors, AuthenticatedUserGetUserinfoData, AuthenticatedUserGetUserinfoResponses, AuthenticatedUserGetUserinfoErrors, AuthenticatedUserUpdateUserinfoData, AuthenticatedUserUpdateUserinfoResponses, AuthenticatedUserUpdateUserinfoErrors, UserGetPageData, UserGetPageResponses, UserGetPageErrors, UserCreateData, UserCreateResponses, UserCreateErrors, UserDeleteData, UserDeleteResponses, UserDeleteErrors, UserGetData, UserGetResponses, UserGetErrors, UserUpdateData, UserUpdateResponses, UserUpdateErrors, UserSetRolesData, UserSetRolesResponses, UserSetRolesErrors, UserPermissionGetAllData, UserPermissionGetAllResponses, UserPermissionGetAllErrors, UserRoleGetPageData, UserRoleGetPageResponses, UserRoleGetPageErrors, UserRoleCreateData, UserRoleCreateResponses, UserRoleCreateErrors, UserRoleDeleteData, UserRoleDeleteResponses, UserRoleDeleteErrors, UserRoleGetDetailData, UserRoleGetDetailResponses, UserRoleGetDetailErrors, UserRoleUpdateData, UserRoleUpdateResponses, UserRoleUpdateErrors, UserRoleSetPermissionsData, UserRoleSetPermissionsResponses, UserRoleSetPermissionsErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Legacy Login
 * ⏱️ Rate limit: `100 per 1 minute`
 */
export const authLegacyLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLegacyLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<AuthLegacyLoginResponses, AuthLegacyLoginErrors, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/login',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options.headers
        }
    });
};

/**
 * Logout
 * ⏱️ Rate limit: `10 per 1 minute`
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<AuthLogoutResponses, AuthLogoutErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/auth/logout',
        ...options
    });
};

/**
 * Get Csrf Token
 * ⏱️ Rate limit: `100 per 1 minute`
 */
export const authGetCsrfToken = <ThrowOnError extends boolean = false>(options?: Options<AuthGetCsrfTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthGetCsrfTokenResponses, AuthGetCsrfTokenErrors, ThrowOnError>({
        url: '/auth/csrf-token',
        ...options
    });
};

/**
 * Get Userinfo
 * ⏱️ Rate limit: `60 per 1 minute`
 */
export const authenticatedUserGetUserinfo = <ThrowOnError extends boolean = false>(options?: Options<AuthenticatedUserGetUserinfoData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<AuthenticatedUserGetUserinfoResponses, AuthenticatedUserGetUserinfoErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/user',
        ...options
    });
};

/**
 * Update Userinfo
 * ⏱️ Rate limit: `60 per 1 minute`
 */
export const authenticatedUserUpdateUserinfo = <ThrowOnError extends boolean = false>(options: Options<AuthenticatedUserUpdateUserinfoData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<AuthenticatedUserUpdateUserinfoResponses, AuthenticatedUserUpdateUserinfoErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/user',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get Page
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:read`
 */
export const userGetPage = <ThrowOnError extends boolean = false>(options?: Options<UserGetPageData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserGetPageResponses, UserGetPageErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users',
        ...options
    });
};

/**
 * Create
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:create`
 */
export const userCreate = <ThrowOnError extends boolean = false>(options: Options<UserCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserCreateResponses, UserCreateErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:delete`
 */
export const userDelete = <ThrowOnError extends boolean = false>(options: Options<UserDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UserDeleteResponses, UserDeleteErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Get
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:read`
 */
export const userGet = <ThrowOnError extends boolean = false>(options: Options<UserGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UserGetResponses, UserGetErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options
    });
};

/**
 * Update
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:update`
 */
export const userUpdate = <ThrowOnError extends boolean = false>(options: Options<UserUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UserUpdateResponses, UserUpdateErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Set Roles
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `users:update`
 */
export const userSetRoles = <ThrowOnError extends boolean = false>(options: Options<UserSetRolesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UserSetRolesResponses, UserSetRolesErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/users/{user_id}/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Get All
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `permissions:read`, `users`, `roles`
 */
export const userPermissionGetAll = <ThrowOnError extends boolean = false>(options?: Options<UserPermissionGetAllData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserPermissionGetAllResponses, UserPermissionGetAllErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/permissions',
        ...options
    });
};

/**
 * Get Page
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:read`
 */
export const userRoleGetPage = <ThrowOnError extends boolean = false>(options?: Options<UserRoleGetPageData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<UserRoleGetPageResponses, UserRoleGetPageErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles',
        ...options
    });
};

/**
 * Create
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:create`
 */
export const userRoleCreate = <ThrowOnError extends boolean = false>(options: Options<UserRoleCreateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<UserRoleCreateResponses, UserRoleCreateErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:delete`
 */
export const userRoleDelete = <ThrowOnError extends boolean = false>(options: Options<UserRoleDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<UserRoleDeleteResponses, UserRoleDeleteErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options
    });
};

/**
 * Get Detail
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:read`
 */
export const userRoleGetDetail = <ThrowOnError extends boolean = false>(options: Options<UserRoleGetDetailData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<UserRoleGetDetailResponses, UserRoleGetDetailErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options
    });
};

/**
 * Update
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:update`
 */
export const userRoleUpdate = <ThrowOnError extends boolean = false>(options: Options<UserRoleUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).patch<UserRoleUpdateResponses, UserRoleUpdateErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Set Permissions
 * ⏱️ Rate limit: `300 per 1 minute`🔓 `roles:update`
 */
export const userRoleSetPermissions = <ThrowOnError extends boolean = false>(options: Options<UserRoleSetPermissionsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UserRoleSetPermissionsResponses, UserRoleSetPermissionsErrors, ThrowOnError>({
        security: [
            {
                in: 'cookie',
                name: 'session',
                type: 'apiKey'
            }
        ],
        url: '/roles/{role_id}/permissions',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};